package com.mangotiger.text;

import static com.mangotiger.text.AnagramDetector.*;
import junit.framework.*;

public class AnagramDetectorTest extends TestCase {

  public void testValidate() throws Exception {
    assertFalse(areAnagrams("abc", "def"));
    assertFalse(areAnagrams(null, "def"));
    assertFalse(areAnagrams("abc", null));
    assertFalse(areAnagrams("abc", ""));
    assertFalse(areAnagrams("", "def"));

    assertTrue(areAnagrams("Dormitory", "Dirty Room"));
    assertTrue(areAnagrams("Dictionary", "Indicatory"));
    assertTrue(areAnagrams("Schoolmaster", "The classroom"));
    assertTrue(areAnagrams("Elvis", "Lives"));
    assertTrue(areAnagrams("Listen", "Silent"));
    assertTrue(areAnagrams("Clint Eastwood", "Old West Action"));
    assertTrue(areAnagrams("Madam Curie", "Radium came"));
    assertTrue(areAnagrams("A telephone girl", "Repeating \"Hello\""));
    assertTrue(areAnagrams("Western Union", "No Wire Unsent"));
    assertTrue(areAnagrams("The country side", "No City Dust Here"));
    assertTrue(areAnagrams("Evangelist", "Evil's Agent"));
    assertTrue(areAnagrams("Astronomers", "Moon starers"));
    assertTrue(areAnagrams("Astronomers", "No more stars"));
    assertTrue(areAnagrams("Postmaster", "Stamp Store"));
    assertTrue(areAnagrams("A telescope", "To see place"));
    assertTrue(areAnagrams("The eyes", "They see"));
    assertTrue(areAnagrams("The ears", "Hear set"));
    assertTrue(areAnagrams("The cockroach", "Cook, catch her"));
    assertTrue(areAnagrams("Waitress", "A stew, Sir?"));
    assertTrue(areAnagrams("The centenarians", "I can hear ten \"tens\""));
    assertTrue(areAnagrams("Desperation", "A rope ends it"));
    assertTrue(areAnagrams("I run to escape", "A persecution"));
    assertTrue(areAnagrams("The Morse Code", "Here Come Dots"));
    assertTrue(areAnagrams("The Meaning of Life", "The fine game of nil"));
    assertTrue(areAnagrams("Slot Machines", "Cash Lost in'em"));
    assertTrue(areAnagrams("Conversation", "Voices Rant On"));
    assertTrue(areAnagrams("Disraeli", "I lead, Sir."));
    assertTrue(areAnagrams("Clothespins", "So let's pinch"));
    assertTrue(areAnagrams("Mr. Mojo risin'", "Jim Morrison"));
    assertTrue(areAnagrams("The Great New York Rapid Transit Tunnel", "Giant work in street, partly underneath"));
    assertTrue(areAnagrams("Florence Nightingale", "Nigel, Fetch an Iron Leg"));
    assertTrue(areAnagrams("Florence Nightingale", "Flit on Cheering Angel"));
    assertTrue(areAnagrams("MacDonalds", "Clam and Sod"));
    assertTrue(areAnagrams("Darling I love you", "leaving your idol"));
    assertTrue(areAnagrams("Darling I love you", "Avoiding our yell"));
    assertTrue(areAnagrams("Butterfly", "Flutter-by"));
    assertTrue(areAnagrams("Heavy Rain?", "Hire a Navy!"));
    assertTrue(areAnagrams("Tom Cruise", "So I'm Cuter"));
    assertTrue(areAnagrams("Animosity", "Is No Amity"));
    assertTrue(areAnagrams("Mother-in-law", "Woman Hitler"));
    assertTrue(areAnagrams("Funeral", "Real Fun"));
    assertTrue(areAnagrams("Protectionism", "Cite no imports"));
    assertTrue(areAnagrams("Protectionism", "Nice to imports"));
    assertTrue(areAnagrams("A domesticated animal", "Docile, as a man tamed it"));
    assertTrue(areAnagrams("The Railroad Train", "Hi! I Rattle and Roar"));
    assertTrue(areAnagrams("The Hilton", "Hint: Hotel"));
    assertTrue(areAnagrams("A Rolling Stone Gathers No Moss", "Stroller on Go, Amasses Nothing"));
    assertTrue(areAnagrams("Sunshine and Shadow", "Show in Sun and Shade"));
    assertTrue(areAnagrams("The Check is in the Mail", "Claim \"Heck, I sent it (heh)\""));
    assertTrue(areAnagrams("The United States Bureau of Fisheries", "I Raise the Bass to Feed Us in the Future"));
    assertTrue(areAnagrams("Snooze Alarms", "Alas! No More Z's"));
    assertTrue(areAnagrams("Vacation Times", "I'm Not as Active"));
    assertTrue(areAnagrams("Vacation time", "I am not active"));
    assertTrue(areAnagrams("Software", "Swear Oft"));
    assertTrue(areAnagrams("Sycophant", "Acts phony"));
    assertTrue(areAnagrams("Silicon Graphics", "A Long Chip Crisis"));
    assertTrue(areAnagrams("Silicon Graphics", "Can logic ship, sir?"));
    assertTrue(areAnagrams("Silicon Graphics", "Gosh, sir, I can clip!"));
    assertTrue(areAnagrams("Alec Guinness", "Genuine Class"));
    assertTrue(areAnagrams("The Detectives", "Detect Thieves"));
    assertTrue(areAnagrams("The Hospital Ambulance", "A Cab, I Hustle to Help Man"));
    assertTrue(areAnagrams("Semolina", "Is No Meal"));
    assertTrue(areAnagrams("The United States of America", "Attaineth its cause, freedom"));
    assertTrue(areAnagrams("Christmas tree", "Search, Set, Trim"));
    assertTrue(areAnagrams("A Gentleman", "Elegant Man"));
    assertTrue(areAnagrams("Presbyterians", "Best In Prayers"));
    assertTrue(areAnagrams("Presbyterians", "Britney Spears"));
    assertTrue(areAnagrams("The Public Art Galleries", "Large Picture Halls, I Bet"));
    assertTrue(areAnagrams("A Decimal Point", "I'm a Dot in Place"));
    assertTrue(areAnagrams("The Earthquakes", "That Queer Shake"));
    assertTrue(areAnagrams("Salman Rushdie", "Read, Shun Islam"));
    assertTrue(areAnagrams("Martin Scorsese", "Screen is a storm"));
    assertTrue(areAnagrams("Barbie doll", "I'll bare bod"));
    assertTrue(areAnagrams("Barbie doll", "Babe I'd roll"));
    assertTrue(areAnagrams("Barbie doll", "Liberal bod"));
    assertTrue(areAnagrams("Student Information Processing Board", "Computation Transgression Forbidden"));
    assertTrue(areAnagrams("Statue of Liberty", "Built to Stay Free"));
    assertTrue(areAnagrams("Eleven plus two", "Twelve plus one"));
    assertTrue(areAnagrams("Patrick Stewart", "A Crap Trek Twist"));
    assertTrue(areAnagrams("Mel Gibson", "Bong Smile"));
    assertTrue(areAnagrams("Admirer", "Married"));
    assertTrue(areAnagrams("Indomitableness", "Endless ambition"));
    assertTrue(areAnagrams("New York Times", "Monkeys write"));
    assertTrue(areAnagrams("New York Times", "Monkey writes"));
    assertTrue(areAnagrams("Television programming", "Permeating living rooms"));
  }
}
